### ISSUE TITLE
Add a toc on top of doxygenclass or doxygennamespace

### ISSUE THREAD

**Issue by alkino** [michaeljones/breathe#182]
Hi,
It's not an issue but a feature request. I like to have a summary of my class or of my namespace just like that:
http://doc.aldebaran.com/2-1/naoqi/core/packagemanager-api.html#packagemanager-api

I will try to add an option for that, but never touch to breathe before...

Regards,

Nicolas

**Comment by michaeljones** [comment]
Hi @alkino,

Thanks for looking at Breathe and for raising this suggestion. I think it would be useful to have and would require some work. I imagine the best way forward to be to copy one of the current directives and add filters such that all the main descriptive content is left out. We'll also have to make sure that no link targets are created only out going links that expect the find the targets elsewhere.

If you're keen to have a look, we'd be more than happy to try to help you through it. Otherwise, we can try to find the time ourselves.

Thanks again,
Michael

**Comment by alkino** [comment]
In fact, I don't know well python / sphinx / breathe. So can't figure how to do that.

Sorry :(

**Comment by michaeljones** [comment]
Thanks for letting me know and sorry it has gone so quiet. I hope we'll get around to this eventually but finding the time is hard.

**Comment by melvinvermeeren** [comment]
I believe either `breathe-apidoc` or https://github.com/svenevs/exhale will do what is desired.

In case I am terribly wrong then I believe #321 will what will resolve this. If not please comment.
