### ISSUE TITLE
Add support for refids to be global

### ISSUE THREAD

**Issue by Andne** [michaeljones/breathe#322]
The current implementation effectively puts the refids for types and such (and even labels) in a project-specific namespace by prefixing the generated id's with the project name.  While this works, it starts to become cumbersome to use when working with a project that is broken up into multiple code-bases.  Especially the auto-generated type links from class definitions have an issue here jumping across boundaries.  I was able to work around this by removing the project name from the generated refId, but this probably is not a good permanent solution, it may break other projects.

I'm guessing the better solution would be to have an option in the sphinx configuration that would allow the user to have project-specific refId's or global refId's.  I can work on the change I think, does it sound like a good idea?  Do we actually need the ability to change this or should all refId's be global?  I don't run into conflicts in my project since the code bases already have a dependency from one to the other so avoid name conflicts through namespaces, but that may not be the case in all projects.

Thoughts?

**Comment by michaeljones** [comment]
Good point! Thanks for raising it and for you ongoing work! If I'm honest, I think the namespacing ids has been in there since very early on and probably didn't have a lot of thought put into it. From your description, I suspect that defaulting to global ids and introducing an option to scope them to projects might be preferable. I would imagine that the most common scenario is to have a single project in which case global is fine, then to have multiple projects that could benefit from referencing it each other, then to have multiple projects that you actually want to sandbox.

It was maybe born out of a need of the documentation where that are lots of different example projects, no need to cross reference and a strong desire to avoid clashes.

I'd support global by default and then some configuration for namespacing.

**Comment by Andne** [comment]
I've added a branch with my changes.  I think I got everything, though the logic to get the config setting may leave something to be desired (commit f6ed73e29dab3d7feab5201085f7068d76d284de).  Take a look and try it out.

**Comment by michaeljones** [comment]
I've merged this into `master`. Would you like a release?

**Comment by Andne** [comment]
I've been looking to see if I have anything else before making another release.  I definitely would like one but it seemed to be extra work to release for each time you merge code.  I do need my open PR included (#324) and I imagine that some others may also have things that would be good to include.
