### ISSUE TITLE
Display value of #define

### ISSUE THREAD

**Issue by amiguels** [michaeljones/breathe#361]
As stated [here](https://stackoverflow.com/questions/48075171/display-value-of-define-using-breath-sphinx), is there a way to show the value of the define? If not, it would be quite useful.

**Comment by svenevs** [comment]
The linked question does not exist anymore, but yes there is.  There's no anchor point to link directly, but search for `ABS` on [this page](https://breathe.readthedocs.io/en/latest/doxygen.html).

Most likely, the reason you aren't getting the `.. doxygendefine` directive working is because you didn't tell Doxygen itself to document it.  Search for `often overlooked` on [this page](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html).

Defines are not documented unless the file itself is documented.  The only other way I know to get this working is [`EXTRACT_ALL`](https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_extract_all).

**Comment by melvinvermeeren** [comment]
I assume this has been solved with the answer above. If there is still an issue with `doxygendefine` feel free to comment.

**Comment by 2bndy5** [comment]
Maybe I'm misunderstanding the OP (because of the dead link). I thought this issue was about getting breathe to show the defined macro's value. If this needs its own issue, please create a new issue from this comment 
![image](https://user-images.githubusercontent.com/14963867/139521900-f9ae3bfd-e162-46b0-a971-14b0a69eb667.png)

## Example
doxygen output:
![image](https://user-images.githubusercontent.com/14963867/139521678-fb1059c4-d61a-446f-8815-571dd72d274a.png)
breathe output (using sphinx-immaterial theme)
![image](https://user-images.githubusercontent.com/14963867/139521723-c9dc2dbf-2950-469f-9847-44eb92e222c4.png)
I also tried using the alabaster theme to make sure it wasn't a problem specific to the sphinx theme, but alas there was no defined macro value. It would be nice if this was addressed, otherwise I'd have to through and add the defined value to all macros' docstr (like seen in the pictures).

It seems the macro's value is output in the XML using the `initializer` tag.
```xml
      <sectiondef kind="define">
      <memberdef kind="define" id="RF24Mesh__config_8h_1a34a829ec67e8c11ed0416fe1ee5e3bae" prot="public" static="no">
        <name>MESH_MAX_CHILDREN</name>
        <initializer>4</initializer>
        <briefdescription>
<para>Set 1 to 4 (Default: 4) Restricts the maximum children per node. </para>
        </briefdescription>
        <detaileddescription>
```

**Comment by 2bndy5** [comment]
Nevermind! I found the `breathe_show_define_initializer` option for conf.py which solves this issue. Sorry.
