### ISSUE TITLE
Provide a changelog with new release

### ISSUE THREAD

**Issue by kbabioch** [michaeljones/breathe#397]
There seems to be no changelog for this project. It is reasonable hard to find what has changed in between versions. A good template could be: https://keepachangelog.com/

**Comment by melvinvermeeren** [comment]
Hi, the changelog for Breathe is located in the main `README.md` instead of the more common `CHANGELOG.md` or similar, for historical reasons I suppose. Perhaps one day I will move the changelog in a separate file.

Since I took over primary maintainership of Breathe I have also added a changelog to tag descriptions, effectively since `v4.8.0`.

**Comment by melvinvermeeren** [comment]
Assuming resolved.
