### ISSUE TITLE
Linking to dot graphs

### ISSUE THREAD

**Issue by hobu** [michaeljones/breathe#45]
It would be really handy to have an option to the renderer that would link back to graphviz output from the HTML renderer of Doxygen.  What I was thinking is an app-level option that takes in the path to the html output of Doxygen, and then an :image: option or some such available to classes (and the index directive too, I suppose), templated classes, etc that simply does an img  link back to that location. 

The app-level option the user gives would simply be the precursor part of the URL that is generated for the img tag. Make sense?

If I want to implement this, what steps should I take?  I fumbled around for #44, and I never really figured out how to bolt options in to do it. Any pointers you can provide to help me bootstrap this would be appreciated.  I'll take on the task once you help me get the ball rolling.

**Comment by guyguy333** [comment]
Hi @michaeljones 

Any news for this feature ?
Do you plan to merge doxygendiagram branch to master ?

Thank you

**Comment by MilesCranmer** [comment]
^I'm also very interested in this

**Comment by melvinvermeeren** [comment]
I have not checked the doxygendiagram branch, but if it is adapted to current Breathe version and implements a "minimal" or "suboptimal" solution then I would still propose merging.

Having basic functionality for this would be better than having none at all in my opinion.

**Comment by SteffenSeckler** [comment]
Even though this is very old, is there any news on this?
Inheritance diagrams would really help understand our code a lot :)

**Comment by samuel-emrys** [comment]
Also very interested in this, @michaeljones do you have any plans to further develop the solution on the `doxygendiagram` branch? If so, have you had any additional thoughts with respect to how you'd like this feature implemented? I might be able to provide some dev effort if you can provide some details about your vision for implementation. I agree with @vermeeren , a minimal or suboptimal implementation provides vastly more value than no implementation at all.

**Comment by orlandini** [comment]
I am loving breathe so far, and this feature would be great. Just showing my support (:

**Comment by 2bndy5** [comment]
I've been trying to figure this lib out (all day), but I can't seem to wrap my head around how the filters work. I'm creating a `docDotFileType` object when `\dotfile` is found within a `para` tag, but it seems to get filtered out somehow. I created a `visit_docdotfile()` function to return a `graphviz` directive object, but it never gets called.

I think something might need to be added to `visit_docpara()`, but I'm pretty much poking around in the dark at this point. 🙈 

ps - the `docDotFileType` seems to have been generated almost 12 years ago but never actually used. Once I get this working, passing a `\dot` cmd to `graphviz` directive should be almost identical.

**Comment by 2bndy5** [comment]
# Success!

Regarding my last post about confusion: I had no idea that the `*SubType` classes were actually doing the parsing from XML. Once the `docParaTypeSub.buildChildren()` was adjusted, progress was made swiftly.

I now have both `\dot` & `\dotfile` cmds being translated into `graphviz` nodes. I also had to replicate some of the code from `Graphviz.run()` in _sphinx.ext.graphviz.py_ as the sphinx directive expects a relative path to the dot file when doxygen xml uses the absolute path instead. Furthermore, I have the captions also being output (when specified) using an rst figure node (exactky like `Graphviz.run()` does).

Instead of posting code changes, I'll submit a PR (after cleaning up my debug print() calls). I'll also be noting some inherent limitations in the upcoming PR...

**Comment by 2bndy5** [comment]
hit a snag when `\ref` cmd is embedded in the dot synatx for cross referencing... Now I have to figure out how this lib handles the `@ref` cmd. My first guess is `addnodes.pending_xref()` used in `visit_docxrefsect()`.

Currently, I'm afraid to alter any dot syntax, but I'll have to experiment more.

**Comment by 2bndy5** [comment]
Given the sample output above and the `graphviz` directive's inability to handle roles embedded in the dot syntax, I'm concluding that we cannot support references using doxygen's `@ref` cmd inside the dot syntax.

I suppose it could be addressed, but we would need doxygen to output a
```xml
<ref refid="..." kindref="...">...</ref>
```
for any occurrences found within the dot syntax (instead of literally text like `@ref ...`).

**Comment by jakobandersen** [comment]
Your progress sounds really good! Please do make a PR when possible to make it easier to discuss details and test it out.

Regarding the ``@ref`` inside Graphviz data I have the same feeling that this may be very difficult to convert correctly, but let's see.

**Comment by 2bndy5** [comment]
I think I need to add to breathe's "Supported Features" docs to highlight the limitations of this approach. After that, I'll submit a PR.

**Comment by 2bndy5** [comment]
## I think I mis-perceived this issue.
My approach only aims to address `\dot` & `\dotfile` cmds which are not the same as the graphs configured by Doxyfile tags. In my research, I found that no XML output is produced for the call/caller/inheritence graphs that _can_ be generated by doxygen. However, the include graphs generated by doxygen (if enabled & relevant) have some output in the header file's XML output.

<details><summary>sample of include graph from header XML</summary>

```xml
    <incdepgraph>
      <node id="1">
        <label>ReceiverCode/src/utilities/common.h</label>
        <link refid="common_8h"/>
        <childnode refid="2" relation="include">
        </childnode>
        <childnode refid="3" relation="include">
        </childnode>
      </node>
      <node id="3">
        <label>EEPROM.h</label>
      </node>
      <node id="2">
        <label>stdint.h</label>
      </node>
    </incdepgraph>
    <invincdepgraph>
      <node id="3">
        <label>ReceiverCode/src/main.cpp</label>
        <link refid="_receiver_code_2src_2main_8cpp"/>
      </node>
      <node id="1">
        <label>ReceiverCode/src/utilities/common.h</label>
        <link refid="common_8h"/>
        <childnode refid="2" relation="include">
        </childnode>
      </node>
      <node id="2">
        <label>ReceiverCode/src/utilities/radio.h</label>
        <link refid="radio_8h"/>
        <childnode refid="3" relation="include">
        </childnode>
      </node>
    </invincdepgraph>
```
</details>

It would take some doing to translate this XML tree to dot syntax (for invocation of sphinx `graphviz` directive). Remember that this sample only addresses the include graphs generated by doxygen.

### I think this issue should be renamed
Since doxygen doesn't require the dot executable to generate the builtin graphs, this issue's title seems misleading. I think doxygen has its own mechanism for these graphs, but it would take a bit of digging in the doxygen src code to find exactly where/how they are generated with/without dot.

**Comment by 2bndy5** [comment]
Done! #757 now supports doxygen generated graphs as well as the doxygen `\dot` & `\dotfile` cmds.
