### ISSUE TITLE
Bit field broken in pybind11 docs

### ISSUE THREAD

**Issue by YannickJadoul** [michaeljones/breathe#462]
I'm not entirely sure how or why, but it seems that the latest release of `breathe` broke the documentation builds of the pybind11 project. The build now fails with the following error:
```
/home/travis/build/pybind/pybind11/docs/reference.rst:60:Invalid definition: Expected end of definition. [error at 25]

  bool arg::flag_noconvert :  1
```

See https://travis-ci.org/pybind/pybind11/jobs/623594114#L354 (and https://travis-ci.org/pybind/pybind11/jobs/616701615 for the last working build).

Relevant line in pybind11:
https://github.com/pybind/pybind11/blob/37352491225358b97ce302273bf2d887a477efb0/include/pybind11/cast.h#L1822

Given that the differences between 4.13.1 and 4.14 are limited, https://github.com/michaeljones/breathe/commit/c2ff07c03b018ebb7888f6ff553c77481fe27116 seems to be a good candidate for the breaking changes. Is pybind11 now using breathe in a wrong way, or is this a corner case that isn't handled correctly by breathe?

(pinging @bstaletic)

**Comment by jakobandersen** [comment]
I believe that your previous build was silently broken, in the sense that the bit field part ``: 1`` was simply stripped by Breathe  (https://pybind11.readthedocs.io/en/stable/reference.html#_CPPv4N3arg14flag_noconvertE).
In Sphinx 2.3 the bit fields are supported (sphinx-doc/sphinx#6707), though it seems the Breathe handling was merged slightly prematurely (#454).
The good news is that if I understand correctly then Sphinx 2.3 is likely to be released in the weekend (sphinx-doc/sphinx#6745), otherwise you can use the 2.0 development branch of Sphinx until 2.3 is released.

**Comment by YannickJadoul** [comment]
@jakobandersen Thanks for the explanation. We'll just pin to 4.13.1 then, until the new sphinx version gets released! :)

**Comment by YannickJadoul** [comment]
This is indeed solved now, with the new version of Sphinx; thank you!
Unfortunately, it seems ReadTheDocs uses an old version of Sphinx (`sphinx<2`; there's some comment about the theme, cfr. [these lines in the readthedocs/readthedocs.org repo](https://github.com/readthedocs/readthedocs.org/blob/be5b0f53b74f1ad94f55523614296edf70b9b452/requirements/pip.txt#L12-L15)), so just using a newer version is not straightforward, it seems. Or do you have any experience with this?

**Comment by melvinvermeeren** [comment]
As posted above should be fixed with current breathe/sphinx versions. RTD theme indeed has issues, for a now time now. Hopefully they will fix those eventually.
