### ISSUE TITLE
Word wrapping for enum values

### ISSUE THREAD

**Issue by senyai** [michaeljones/breathe#476]
Hello! 

  `.. doxygenenum:: TangleCheckResult` will result in:

![image](https://user-images.githubusercontent.com/76137/75272790-97a2bd00-580f-11ea-8877-3003e65b45b8.png)

  that is, the value of `TCR_INDEPENDENT_IMAGES` is partly hidden when this enum is used:

```
typedef enum {
  TCR_FORWARD_PASS_POSSIBLE  = 0x01,
  TCR_BACKWARD_PASS_POSSIBLE = 0x02,
  TCR_INDEPENDENT_LINES      = 0x04,
  TCR_INDEPENDENT_IMAGES     = TCR_FORWARD_PASS_POSSIBLE |
                               TCR_BACKWARD_PASS_POSSIBLE |
                               TCR_INDEPENDENT_LINES,
  ///< Images do not intersect in memory.
} TangleCheckResult;
```

**Comment by jakobandersen** [comment]
Is this with html output? or something else?
I suspect that the issue is not specific for Breathe-assisted documentation, but would happen with raw Sphinx input. Try with something like the following:
```rst
.. cpp:enumerator:: TCR_INDEPENDENT_IMAGES     = TCR_FORWARD_PASS_POSSIBLE | \
                               TCR_BACKWARD_PASS_POSSIBLE | \
                               TCR_INDEPENDENT_LINES
```
If so it would be good to open an issue over there, preferably with an archive with a minimal non-Breathe example for reproduction and experimentation.

**Comment by senyai** [comment]
Sorry, it was pdf output. Yes, this is sphinx issue, so let's close this one.
