### ISSUE TITLE
requirements prevent use of Sphinx 3.1.0

### ISSUE THREAD

**Issue by jmckenna** [michaeljones/breathe#541]
- Sphinx 3.1.0 has been released today (https://github.com/sphinx-doc/sphinx/blob/3.x/CHANGES)
 - currently breathe requirements are forced to be` Sphinx>=3.0,<3.1` (related to recent change through #498)
 - suggest to bump up the Sphinx version requirements

**Comment by jakobandersen** [comment]
If I remember correctly there should be no Sphinx changes to prevent a bump to ``Sphinx>=3.0,<3.2``.
There may be cases in the documentation that could benefit from
> * C, added scope control directives, :rst:dir:`c:namespace`,
  :rst:dir:`c:namespace-push`, and :rst:dir:`c:namespace-pop`.

Perhaps we should open an issue accumulating TODOs for an overview of when it may be beneficial to raise to lower Sphinx version bound.

**Comment by vermeeren** [comment]
@jmckenna Fixed in breathe v4.19.1, just released it. Thanks for the issue.

@jakobandersen Yeah I think that would be a good idea, we could also document it in some COMPATIBILITY.md file in the repository, that might be easier to track long-term. I am fine with both cases.

(Appears the Sphinx branch 3.0.x has been removed, will update CICD in a sec.)

**Comment by jmckenna** [comment]
Verified here.  Thanks for the quick fix @vermeeren
