### ISSUE TITLE
How to fine tune output of doxygenclass::

### ISSUE THREAD

**Issue by steffenroeber** [michaeljones/breathe#582]
Hi,
I'd like to have something like Qt uses for its documentation:
- include header file
- class name
- brief docu
- outlined members
- detailed docu
- detailed members
I tried it like:
```
*****************
AbstractTransform
*****************

Header: #include<cbl/AbstractTransform.h>

.. doxygenclass:: cassandra::math::AbstractTransform

.. doxygenclass:: cassandra::math::AbstractTransform
   :members:   
   :outline:

.. doxygenclass:: cassandra::math::AbstractTransform
   :members:   

```
but this gives me warnings like:
`Warning: Duplicate target detected:`
and duplicates output of class name.

Best regards
Steffen

**Comment by vermeeren** [comment]
@steffenroeber What is the intention effectively? To have a custom defined print order for `doxygenclass` command?

**Comment by steffenroeber** [comment]
Yes, exactly. I like the style of Qt docu and wanted getting some similar at our project.

**Comment by vermeeren** [comment]
@steffenroeber I don't think this is possible currently, there is https://breathe.readthedocs.io/en/latest/directives.html#confval-breathe_order_parameters_first but this is only partial configuration via a bool and not as flexible as needed for such a thing.

Ideally Breathe would gain a configuration setting that allows for fully specified output order. Specifically for `doxygenfile` and `autodoxygenfile` there is some way to do things with `section` option.

I think this issue is effectively the same as #520 in its goal, is it ok to close as duplicate?

**Comment by steffenroeber** [comment]
Ok, sounds reasonable. Thanx
