### ISSUE TITLE
Different parameter/return rendering from official sphinx

### ISSUE THREAD

**Issue by markand** [michaeljones/breathe#599]
Hello,

I was planning to use Breathe because I love the sphinx documentation output but I hate doxygen's one. I have plugged in into one of my small pet project and was pretty happy with the result. I've tried it with the popular `sphinx_rtd_theme` and I just saw an issue about the style of parameter/returns that look different than using sphinx official directives.

Example with a small function:

```
.. c:function:: void burn(int x)

   :param x: Index.
   :returns: Nothing.

Destroy everything.
```

Will be rendered like this:

<img width="301" alt="Screenshot 2020-11-07 at 16 40 08" src="https://user-images.githubusercontent.com/11919008/98445416-fe56d500-2117-11eb-98dc-cc4007211cb1.png">

But linking a function generated by doxygen is rendered like this:

<img width="743" alt="Screenshot 2020-11-07 at 16 40 16" src="https://user-images.githubusercontent.com/11919008/98445426-0ca4f100-2118-11eb-85c1-dcc6e651da6c.png">

See the grey box around "Pre/Parameters" block. Is there a chance that we can have the same style as using default directives? As my project also has a non-doxygen API it creates some inconsistencies.

**Comment by vermeeren** [comment]
@markand This probably happens because Breathe has its own renderer for many things, mostly because of historical reasons. You can check the renderer code in `breathe/renderer/sphinxrenderer.py`. Functions `visit_docparamlist` and `visit_param` are a starting point.

Matching Sphinx's native style is the goal, so patches are very welcome.
