### ISSUE TITLE
IndexError: list index out of range on sphinxrenderer.py rst_node = nodes[1]

### ISSUE THREAD

**Issue by neel** [michaeljones/breathe#671]
#308 (marked close) reappeared.

Sphinx giving the following error and not generating the HTML output

```
Exception occurred:
  File "/usr/lib/python3.9/site-packages/breathe/renderer/sphinxrenderer.py", line 611, in run_directive
    rst_node = nodes[1]
IndexError: list index out of range
```

Reference issue: https://github.com/sphinx-doc/sphinx/issues/9070

**Comment by jakobandersen** [comment]
This is definitely a bug, and #672 should fix it. Though, the reason for it to trigger is icky:
In the output you should have the message
```
/dhyara/docs/source/api/structdhyara_1_1packets_1_1chunk.rst.rst:23: WARNING: C++ declarations inside functions are not supported. Parent function: dhyara::packets::chunk::header
Directive name: cpp:var
Directive arg:  raw_address_type _target
```
If you in ``conf.py`` insert ``breathe_debug_trace_directives = True`` you can see the declarations that Breathe generates and runs in Sphinx.
The problem is that in ``includes/dhyara/packets/chunk.h`` you have a class ``dhyara::packets::chunk::header``, but also a member function with the same name. The function seems to be added to Sphinx first, making the class a duplicate name, and the variable ``_target`` is then added in the function scope.
While this name hiding of the class is valid C++, the domain in Sphinx currently doesn't support it, and I'm not sure it is easy to make it work.
