### ISSUE TITLE
tparam not recognized for classes

### ISSUE THREAD

**Issue by chausner-audeering** [michaeljones/breathe#761]
Breathe is incorrectly translating template parameter annotations for classes. E.g.
```c++
/// @brief Test
/// @tparam E the type parameter
template <typename E>
class Test {}
```

is rendered in HTML as:

![image](https://user-images.githubusercontent.com/64791786/141687246-064ab852-0117-4178-b1df-c47ae563313c.png)

It does work correctly for free functions, e.g.:
```c++
/// @brief Test
/// @tparam E the type parameter
template <typename E>
void Test() {}
```

is rendered as expected as:

![image](https://user-images.githubusercontent.com/64791786/141687330-d89c28eb-29df-40e5-bab9-4a2f894a7bcb.png)

I checked the XML output of Doxygen and did not notice anything wrong, so I assume it must be an issue in Breathe. I am using Breathe 4.31.0, Sphinx 4.2.0 and Doxygen 1.9.1.

**Comment by michaeljones** [comment]
Thanks for reporting it.

**Comment by 2bndy5** [comment]
Ironically, I've been looking into this exact problem without knowing that this issue was created. If you look at the XML, the `parameterlist` is part of the `compounddef` for classes. But the `parameterlist` for functions is part of the `memberdef` of a compound. This subtle difference is why the template parameter list is handled differently.

Unfortunately, I don't see a simple solution for this (yet). After parsing the XML, the `parameterlist`s make their way to the same function (`visit_docparamlist()`) which seems to arbitrarily do the same thing despite whatever the `parameterlist`'s parent node is. I have a feeling that the `visit_docparamlist()` needs to be passed some extra context (perhaps as part of the `parameterlistType` node). Or maybe its something simpler, and I'm just overthinking it.

**Comment by chausner-audeering** [comment]
@2bndy5 Thanks for sharing your insights. I'm wondering for how long this issue has been existing. Can we maybe revert to an older version of Breathe as a temporary workaround?

**Comment by 2bndy5** [comment]
I guess. I wouldn't know which version would work better (if at all). I only recently (like a couple weeks ago) started figuring out this extension's underlying mechanics.

If you know/find a version that doesn't have this problem please share it.

**Comment by jakobandersen** [comment]
I think it has to do with the field-list handling at https://github.com/michaeljones/breathe/blob/aec47028e05ad8d77e960db9d25140e9fd1c0127/breathe/renderer/sphinxrenderer.py#L867.
The doctree I get for the class is something like
```xml
        <desc_content>
            <paragraph>Test. </paragraph>
            <paragraph><field_list><field><field_name>tparam E</field_name><field_body><paragraph>the type parameter </paragraph></field_body></field></field_list></paragraph>
        </desc_content>
```
i.e., with the ``field_list`` inside a paragraph. But it must be top-level in ``desc_content`` for Sphinx to process it.
The doctree I get for the function has it at top-level:
```xml
        <desc_content>
            <paragraph>Test. </paragraph>
            <field_list>
                <field>
                    <field_name>Template Parameters</field_name>
                    <field_body>
                        <paragraph><literal_strong>E</literal_strong> – the type parameter </paragraph>
                    </field_body>
                </field>
            </field_list>
        </desc_content>
```

**Comment by 2bndy5** [comment]
I still need a way to differentiate between the template parameter list of  a class/function. This is not an easy fix as the `parameterlist` is nested 2 levels deep from any identifying `compounddef` or `memberdef` node. I think the most ideal approach is to have something in `depart_compound()` to signal this difference.

**Comment by 2bndy5** [comment]
@jakobandersen It was a dead lead. the `description()` only handles objects of type `memberdefTypeSub` or `enumvalueTypeSub`. I'm still stumped because (as I said before) the problematic template param list only exists in the 
- `compounddef` -> `detaileddescription` 
- not `compounddef` -> `memeberdef` -> `detaileddescription`

**Comment by jakobandersen** [comment]
See #764. Can you try it out? I think it should fix the problem.

**Comment by chausner-audeering** [comment]
Great, that was quick! Thanks a lot @michaeljones @2bndy5 @jakobandersen for your insights and fix for this issue. Looking forward to testing it with the next Breathe release.
