### ISSUE TITLE
Code highlighting does not account for unparsed case

### ISSUE THREAD

**Issue by gmarull** [michaeljones/breathe#805]
It looks like additions made in https://github.com/michaeljones/breathe/pull/760 don't account for the `unparsed` case:

```
 \code{.unparsed}
  Show this as-is please
  \endcode
```

Pygments highlighter doesn't support this _language_, and so it ends up generating a warning during build process.

**Comment by 2bndy5** [comment]
well, I guess we could add a specific case for this language (never heard of a file extension called .unparsed), but my first impression is that it is more of an issue with pygments.

If you don't want syntax highlighting, then you should provide a doxygen with a `.txt` file extension.
![image](https://user-images.githubusercontent.com/14963867/154043101-1e59d136-1de0-4003-9989-70fba2e85f94.png)
There might be a chance that pygments could guess that the syntax is CMake script, but I doubt that would be a problem because breathe tells pygments what lexer to use (via pygments API) when doxygen's `\code` block is provided a filename arg.

**Comment by 2bndy5** [comment]
oh! I just found this in the doxygen manual

>If the contents of the code block are in a language that doxygen cannot parse, doxygen will just show the output as-is. You can make this explicit using .unparsed, or by giving some other extension that doxygen doesn't support

Looks like we should add this special case due to doxygen's limited syntax highlighting. I still think, that using `.txt` is more acceptable than something specific to doxygen because doygen doesn't support a .txt extension within doxygen's list of supported language parsers.

**Comment by gmarull** [comment]
I think breathe really needs to support Doxygen syntax, that is, ignore `.unparsed` case. Otherwise, breathe is really breaking Doxygen compatibility.

**Comment by 2bndy5** [comment]
I'm already looking into a solution that does just that. Seems there was some more changes pushed to that PR that I didn't track...

**Comment by 2bndy5** [comment]
I submitted a patch for this.

@gmarull Thank you again for commenting on the appropriate PR. I'm not a maintaining member, so I'm not subscribed to all breathe-related notifications.
