### ISSUE TITLE
Breathe outputting`X are not documented` even when Doxyfile ignores that warning

### ISSUE THREAD

**Issue by iquah1** [michaeljones/breathe#815]
Hi there! 

I'm running into a bit of an issue whereby Breathe (I think) is still spitting out the above even when the Doxyfile specifies to avoid doing so.

The repo in question [OpenFHE-temp](https://github.com/openfheorg/openfhe-temp/tree/documentation), the [conf.py](https://github.com/openfheorg/openfhe-temp/blob/documentation/docs/conf.py), the [Doxyfile.in](https://github.com/openfheorg/openfhe-temp/blob/documentation/docs/Doxyfile.in) (which gets processed), and the [CMakeLists](https://github.com/openfheorg/openfhe-temp/blob/documentation/docs/CMakeLists.txt)

**Comment by 2bndy5** [comment]
It would help narrow down if this is indeed a breathe problem if you submitted a simple example that can reproduce the error. Info dumping the config and source code will not yield an adequate diagnosis because we're not familiar with the project in question.

The issue title seems a bit too terse to understand the problem here. It would help more if we could see the full error message in the docs' build log. Looking at the repo's CI runs/jobs, I'm not sure where to find the docs' build log output.

**Comment by iquah1** [comment]
@2bndy5 Sorry, I'm opening a new issue now that better targets what I want/ need
