### ISSUE TITLE
Research and add Breathe docs to Readthedocs.org if possible

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/breathe#89]
It is fast becoming the Python project default and would lead to more up to date docs if they are constantly rebuilt from the latest on the `master` branch rather than waiting for me to update them.

**Comment by sjm324** [comment]
Hi @michaeljones, thanks for breathe :)  I was trying to figure out how all of the pieces fit together (doxygen, sphinx, breathe, readthedocs, etc.) and finally found this post.  I think it would be really useful if you add the example repo you found: https://github.com/Cruel/readthedocs-breathe .  It would probably be enough to link it at at the bottom of http://breathe.readthedocs.org/en/readthedocs/readthedocs.html ?

The [sphinx build process](http://read-the-docs.readthedocs.io/en/latest/builds.html#packages-installed-in-the-build-environment) explicitly lists `doxygen` as of this time, but not `breathe`.  My understanding (through failure) is that I am missing

1. *Not* using a separate source and build, and that seems to break on RTD.
2. In order to include 'breathe' in the `extensions` list in `conf.py` you need the related line in `requirements.txt`.

Both of which were described on this thread.  Though excellent, the RTD docs are somewhat vague about what is called when.  My project uses `CMake` and having a `setup.py` in the root directory would be misleading / not as nice.  I still don't have things working, but I suspect that repo's strategy is valid and I think it would be good to link to it from your breathe RTD.
